Repository MotooriKashin/bilibiliplayer, pull requests merged in 2022-12, with the labels that each got.

#11 fix: popup danmaku style
  bilibiliplayer/bilibiliPlayer.ts
  bilibiliplayer/css/index.less
  bilibiliplayer/css/popup.less
  bilibiliplayer/css/recommend.less
  bilibiliplayer/jquery/1.7.2/jquery.min.js
  bilibiliplayer/js/io/rebuild-player-extra-params.ts
  bilibiliplayer/js/player/danmaku.ts
  bilibiliplayer/js/player/ending-panel.ts
  bilibiliplayer/js/player/video-top.ts
  player-auxiliary/js/panel/recommend.ts
Labels: bug, enhancement

#14 using danmakuArray.concat
  player-auxiliary/js/panel/danmaku-list.ts
Labels: enhancement

#18 fix: relative url of style
  README.md
  b-back/static/index.less
  bilibiliplayer/css/index.less
Labels: bug

#20 feat: Danmaku append
  bilibiliplayer/bilibiliPlayer.ts
  bilibiliplayer/css/index.less
  bilibiliplayer/js/const/player-directive.ts
  bilibiliplayer/js/io/api-user-status.ts
  bilibiliplayer/js/player/controller.ts
  bilibiliplayer/js/player/controller/quality.ts
  bilibiliplayer/js/player/danmaku.ts
  bilibiliplayer/js/player/directive-manager.ts
  bilibiliplayer/js/player/mode-selection.ts
  bilibiliplayer/js/player/proto/load-pb.ts
  bilibiliplayer/js/player/user.ts
  bilibiliplayer/js/plugins/context-menu.ts
  player-auxiliary/js/const/player-directive.ts
  player-auxiliary/js/panel/danmaku-list.ts
  player-auxiliary/js/panel/playlist-origin.ts
  player-auxiliary/js/panel/playlist.ts
  player-auxiliary/js/panel/user.ts
  player-auxiliary/js/panel/watchlater.ts
Labels: bug, enhancement
